// npm run balance → balance/report.md. Commit the result: every PR that changes a number shows its effect.
import { writeFileSync } from 'node:fs';
import { XP_TABLE, MAX_LEVEL, levelForXp } from '@/content/formulas';
import { ZONES } from '@/content/monsters';
import { combatHours, fight, fletching, gathering, rules, smithing, totalHours, WEAPON_STYLES } from '@/balance/model';

const n = (v: number, d = 0) => v.toLocaleString('en-NZ', { maximumFractionDigits: d, minimumFractionDigits: d });
const k = (v: number) => (v >= 10_000 ? `${n(v / 1000)}k` : v >= 1000 ? `${n(v / 1000, 1)}k` : n(v));
const h = (v: number) => (v < 1 ? `${n(v * 60)} min` : `${n(v, 1)} h`);
const pct = (v: number) => `${n(v * 100)}%`;
/** Numeric columns right-align; text columns stay left. */
const table = (head: string[], rows: (string | number)[][]) => {
  const numeric = head.map((_, i) => i > 0 && rows.every((r) => /^[-−+]?[\d.,]+\s*(%|k|h|s|g|min|h each)?$/.test(String(r[i]))));
  return [`| ${head.join(' | ')} |`, `| ${head.map((_, i) => (numeric[i] ? '---:' : '---')).join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
};

const wc = gathering('woodcutting'), mine = gathering('mining'), fish = gathering('fishing');
const smith = smithing(), fletch = fletching(), combat = combatHours();
const combatTotal = totalHours(combat);
const grand = totalHours(wc) + totalHours(mine) + totalHours(fish) + totalHours(smith.map((r) => ({ hours: r.anvilHours }))) + totalHours(fletch.map((r) => ({ hours: r.benchHours }))) + combatTotal * 4;
const results = rules();

const gatherTable = (rows: ReturnType<typeof gathering>) =>
  table(['Node', 'Lv', 'Time', 'XP', 'Value', 'XP/h', 'Gold/h', 'Time in tier'], rows.map((r) => [r.name, r.level, `${r.seconds}s`, r.xp, `${r.value}g`, k(r.xpPerHour), k(r.goldPerHour), h(r.hours)]));

const md = `# Ironbark balance report

Generated by \`npm run balance\` from \`src/content\`. Do not edit by hand.

## Rules

${results.map((r) => `- ${r.pass ? '✅' : '❌'} **${r.rule}** — ${r.detail}`).join('\n')}

## Time to 99

${table(['Skill', '1 → 99', 'How it is counted'], [
  ['Woodcutting', h(totalHours(wc)), 'best tree, same-tier axe'],
  ['Mining', h(totalHours(mine)), 'best rock, same-tier pickaxe'],
  ['Fishing', h(totalHours(fish)), 'best fish, same-tier rod'],
  ['Smithing', h(totalHours(smith.map((r) => ({ hours: r.anvilHours })))), `at the anvil, plus ${h(totalHours(smith.map((r) => ({ hours: r.supplyHours }))))} of mining`],
  ['Fletching', h(totalHours(fletch.map((r) => ({ hours: r.benchHours })))), `at the bench, plus ${h(totalHours(fletch.map((r) => ({ hours: r.supplyHours }))))} of woodcutting`],
  ['Attack / Strength / Defense / Ranged', `${h(combatTotal)} each`, "each zone's middle monster, same-tier gear"],
  ['Everything', h(grand), 'Hitpoints lands near 99 alongside the others'],
])}

XP to 99: ${n(XP_TABLE[MAX_LEVEL])}. Half of that is level ${levelForXp(XP_TABLE[MAX_LEVEL] / 2)}.

## Woodcutting

${gatherTable(wc)}

## Mining

${gatherTable(mine)}

## Fishing

${gatherTable(fish)}

## Smithing

${table(['Bar', 'Lv', 'XP/bar', 'Bars in tier', 'Mining to supply', 'At the anvil', 'Bar value', 'Ore value'], smith.map((r) => [r.name, r.level, r.xpPerBar, n(r.bars), h(r.supplyHours), h(r.anvilHours), `${r.barValue}g`, `${r.oreValue}g`]))}

## Fletching

${table(['Wood', 'Lv', 'XP/log', 'Logs in tier', 'Cutting to supply', 'At the bench'], fletch.map((r) => [r.name, r.level, r.xpPerLog, n(r.logs), h(r.supplyHours), h(r.benchHours)]))}

## Combat (sword, typical same-tier player)

${table(['Zone', 'Monster', 'Lv', 'HP', 'Max hit', 'You hit', 'It hits', 'Kill', 'XP/h', 'Gold/h', 'Food/h', 'Fishing min/h'], ZONES.flatMap((z) => z.monsters.map((m) => {
  const f = fight(m, 'sword');
  return [z.name, m.name, m.level, n(m.hp), m.maxHit, pct(f.yourHit), pct(f.theirHit), `${n(f.killSeconds)}s`, k(f.xpPerHour), k(f.goldPerHour), n(f.foodPerHour), n(f.fishingMinutes, 1)];
})))}

## Weapons vs the sword (XP/h)

${table(['Monster', ...WEAPON_STYLES.slice(1)], ZONES.flatMap((z) => z.monsters).map((m) => {
  const base = fight(m, 'sword').xpPerHour;
  return [m.name, ...WEAPON_STYLES.slice(1).map((st) => `${n((fight(m, st).xpPerHour / base - 1) * 100)}%`)];
}))}
`;

writeFileSync(new URL('./report.md', import.meta.url), md);
const failed = results.filter((r) => !r.pass);
console.log(`balance/report.md written. ${results.length - failed.length}/${results.length} rules pass. Everything to 99: ${h(grand)}.`);
for (const f of failed) console.log(`  ✗ ${f.rule}: ${f.detail}`);
if (failed.length) process.exitCode = 1;
